version: "3"

services:
  init-fairyringdnode0:
    container_name: fairyringdnode0
    image: "fairyring:latest"
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-fairyringd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - ./.testnets:/data:Z
    command: "setup.sh validator0"
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  fairyringdnode1:
    container_name: fairyringdnode1
    image: "fairyring:latest"
    environment:
      - DEBUG=0
      - ID=1
      - LOG=${LOG:-fairyringd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    volumes:
      - ./.testnets:/data:Z
    command: "setup.sh validator1"
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  fairyringdnode2:
    container_name: fairyringdnode2
    image: "fairyring:latest"
    environment:
      - DEBUG=0
      - ID=2
      - LOG=${LOG:-fairyringd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
      - "2347:2345"
    volumes:
      - ./.testnets:/data:Z
    command: "setup.sh validator2"
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  fairyringdnode3:
    container_name: fairyringdnode3
    image: "fairyring:latest"
    environment:
      - DEBUG=0
      - ID=3
      - LOG=${LOG:-fairyringd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
      - "2348:2345"
    volumes:
      - ./.testnets:/data:Z
    command: "setup.sh validator3"
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25