// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fairyring/ckks/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgSubmitPkgShare struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ShareData string `protobuf:"bytes,2,opt,name=shareData,proto3" json:"shareData,omitempty"`
}

func (m *MsgSubmitPkgShare) Reset()         { *m = MsgSubmitPkgShare{} }
func (m *MsgSubmitPkgShare) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPkgShare) ProtoMessage()    {}
func (*MsgSubmitPkgShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{2}
}
func (m *MsgSubmitPkgShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPkgShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitPkgShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitPkgShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPkgShare.Merge(m, src)
}
func (m *MsgSubmitPkgShare) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPkgShare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPkgShare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPkgShare proto.InternalMessageInfo

func (m *MsgSubmitPkgShare) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitPkgShare) GetShareData() string {
	if m != nil {
		return m.ShareData
	}
	return ""
}

type MsgSubmitPkgShareResponse struct {
}

func (m *MsgSubmitPkgShareResponse) Reset()         { *m = MsgSubmitPkgShareResponse{} }
func (m *MsgSubmitPkgShareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPkgShareResponse) ProtoMessage()    {}
func (*MsgSubmitPkgShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{3}
}
func (m *MsgSubmitPkgShareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitPkgShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitPkgShareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitPkgShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPkgShareResponse.Merge(m, src)
}
func (m *MsgSubmitPkgShareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitPkgShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPkgShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPkgShareResponse proto.InternalMessageInfo

type MsgSubmitRkgShareRound1 struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ShareData string `protobuf:"bytes,2,opt,name=shareData,proto3" json:"shareData,omitempty"`
}

func (m *MsgSubmitRkgShareRound1) Reset()         { *m = MsgSubmitRkgShareRound1{} }
func (m *MsgSubmitRkgShareRound1) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitRkgShareRound1) ProtoMessage()    {}
func (*MsgSubmitRkgShareRound1) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{4}
}
func (m *MsgSubmitRkgShareRound1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitRkgShareRound1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitRkgShareRound1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitRkgShareRound1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitRkgShareRound1.Merge(m, src)
}
func (m *MsgSubmitRkgShareRound1) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitRkgShareRound1) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitRkgShareRound1.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitRkgShareRound1 proto.InternalMessageInfo

func (m *MsgSubmitRkgShareRound1) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitRkgShareRound1) GetShareData() string {
	if m != nil {
		return m.ShareData
	}
	return ""
}

type MsgSubmitRkgShareRound1Response struct {
}

func (m *MsgSubmitRkgShareRound1Response) Reset()         { *m = MsgSubmitRkgShareRound1Response{} }
func (m *MsgSubmitRkgShareRound1Response) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitRkgShareRound1Response) ProtoMessage()    {}
func (*MsgSubmitRkgShareRound1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{5}
}
func (m *MsgSubmitRkgShareRound1Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitRkgShareRound1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitRkgShareRound1Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitRkgShareRound1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitRkgShareRound1Response.Merge(m, src)
}
func (m *MsgSubmitRkgShareRound1Response) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitRkgShareRound1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitRkgShareRound1Response.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitRkgShareRound1Response proto.InternalMessageInfo

type MsgSubmitRkgShareRound2 struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ShareData string `protobuf:"bytes,2,opt,name=shareData,proto3" json:"shareData,omitempty"`
}

func (m *MsgSubmitRkgShareRound2) Reset()         { *m = MsgSubmitRkgShareRound2{} }
func (m *MsgSubmitRkgShareRound2) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitRkgShareRound2) ProtoMessage()    {}
func (*MsgSubmitRkgShareRound2) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{6}
}
func (m *MsgSubmitRkgShareRound2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitRkgShareRound2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitRkgShareRound2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitRkgShareRound2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitRkgShareRound2.Merge(m, src)
}
func (m *MsgSubmitRkgShareRound2) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitRkgShareRound2) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitRkgShareRound2.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitRkgShareRound2 proto.InternalMessageInfo

func (m *MsgSubmitRkgShareRound2) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitRkgShareRound2) GetShareData() string {
	if m != nil {
		return m.ShareData
	}
	return ""
}

type MsgSubmitRkgShareRound2Response struct {
}

func (m *MsgSubmitRkgShareRound2Response) Reset()         { *m = MsgSubmitRkgShareRound2Response{} }
func (m *MsgSubmitRkgShareRound2Response) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitRkgShareRound2Response) ProtoMessage()    {}
func (*MsgSubmitRkgShareRound2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{7}
}
func (m *MsgSubmitRkgShareRound2Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitRkgShareRound2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitRkgShareRound2Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitRkgShareRound2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitRkgShareRound2Response.Merge(m, src)
}
func (m *MsgSubmitRkgShareRound2Response) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitRkgShareRound2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitRkgShareRound2Response.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitRkgShareRound2Response proto.InternalMessageInfo

type MsgSubmitGkgShare struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ShareData string `protobuf:"bytes,2,opt,name=shareData,proto3" json:"shareData,omitempty"`
}

func (m *MsgSubmitGkgShare) Reset()         { *m = MsgSubmitGkgShare{} }
func (m *MsgSubmitGkgShare) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitGkgShare) ProtoMessage()    {}
func (*MsgSubmitGkgShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{8}
}
func (m *MsgSubmitGkgShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitGkgShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitGkgShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitGkgShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitGkgShare.Merge(m, src)
}
func (m *MsgSubmitGkgShare) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitGkgShare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitGkgShare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitGkgShare proto.InternalMessageInfo

func (m *MsgSubmitGkgShare) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitGkgShare) GetShareData() string {
	if m != nil {
		return m.ShareData
	}
	return ""
}

type MsgSubmitGkgShareResponse struct {
}

func (m *MsgSubmitGkgShareResponse) Reset()         { *m = MsgSubmitGkgShareResponse{} }
func (m *MsgSubmitGkgShareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitGkgShareResponse) ProtoMessage()    {}
func (*MsgSubmitGkgShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{9}
}
func (m *MsgSubmitGkgShareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitGkgShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitGkgShareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitGkgShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitGkgShareResponse.Merge(m, src)
}
func (m *MsgSubmitGkgShareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitGkgShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitGkgShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitGkgShareResponse proto.InternalMessageInfo

type MsgSubmitShamirShare struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ShareList string `protobuf:"bytes,2,opt,name=shareList,proto3" json:"shareList,omitempty"`
}

func (m *MsgSubmitShamirShare) Reset()         { *m = MsgSubmitShamirShare{} }
func (m *MsgSubmitShamirShare) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitShamirShare) ProtoMessage()    {}
func (*MsgSubmitShamirShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{10}
}
func (m *MsgSubmitShamirShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitShamirShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitShamirShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitShamirShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitShamirShare.Merge(m, src)
}
func (m *MsgSubmitShamirShare) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitShamirShare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitShamirShare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitShamirShare proto.InternalMessageInfo

func (m *MsgSubmitShamirShare) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitShamirShare) GetShareList() string {
	if m != nil {
		return m.ShareList
	}
	return ""
}

type MsgSubmitShamirShareResponse struct {
}

func (m *MsgSubmitShamirShareResponse) Reset()         { *m = MsgSubmitShamirShareResponse{} }
func (m *MsgSubmitShamirShareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitShamirShareResponse) ProtoMessage()    {}
func (*MsgSubmitShamirShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{11}
}
func (m *MsgSubmitShamirShareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitShamirShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitShamirShareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitShamirShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitShamirShareResponse.Merge(m, src)
}
func (m *MsgSubmitShamirShareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitShamirShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitShamirShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitShamirShareResponse proto.InternalMessageInfo

type MsgKeySwitchRequest struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Ct      string `protobuf:"bytes,2,opt,name=ct,proto3" json:"ct,omitempty"`
	NewPk   string `protobuf:"bytes,3,opt,name=newPk,proto3" json:"newPk,omitempty"`
}

func (m *MsgKeySwitchRequest) Reset()         { *m = MsgKeySwitchRequest{} }
func (m *MsgKeySwitchRequest) String() string { return proto.CompactTextString(m) }
func (*MsgKeySwitchRequest) ProtoMessage()    {}
func (*MsgKeySwitchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{12}
}
func (m *MsgKeySwitchRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgKeySwitchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgKeySwitchRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgKeySwitchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgKeySwitchRequest.Merge(m, src)
}
func (m *MsgKeySwitchRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgKeySwitchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgKeySwitchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgKeySwitchRequest proto.InternalMessageInfo

func (m *MsgKeySwitchRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgKeySwitchRequest) GetCt() string {
	if m != nil {
		return m.Ct
	}
	return ""
}

func (m *MsgKeySwitchRequest) GetNewPk() string {
	if m != nil {
		return m.NewPk
	}
	return ""
}

type MsgKeySwitchRequestResponse struct {
}

func (m *MsgKeySwitchRequestResponse) Reset()         { *m = MsgKeySwitchRequestResponse{} }
func (m *MsgKeySwitchRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgKeySwitchRequestResponse) ProtoMessage()    {}
func (*MsgKeySwitchRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1c4b5cf36db7d93, []int{13}
}
func (m *MsgKeySwitchRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgKeySwitchRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgKeySwitchRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgKeySwitchRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgKeySwitchRequestResponse.Merge(m, src)
}
func (m *MsgKeySwitchRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgKeySwitchRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgKeySwitchRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgKeySwitchRequestResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "fairyring.ckks.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "fairyring.ckks.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgSubmitPkgShare)(nil), "fairyring.ckks.MsgSubmitPkgShare")
	proto.RegisterType((*MsgSubmitPkgShareResponse)(nil), "fairyring.ckks.MsgSubmitPkgShareResponse")
	proto.RegisterType((*MsgSubmitRkgShareRound1)(nil), "fairyring.ckks.MsgSubmitRkgShareRound1")
	proto.RegisterType((*MsgSubmitRkgShareRound1Response)(nil), "fairyring.ckks.MsgSubmitRkgShareRound1Response")
	proto.RegisterType((*MsgSubmitRkgShareRound2)(nil), "fairyring.ckks.MsgSubmitRkgShareRound2")
	proto.RegisterType((*MsgSubmitRkgShareRound2Response)(nil), "fairyring.ckks.MsgSubmitRkgShareRound2Response")
	proto.RegisterType((*MsgSubmitGkgShare)(nil), "fairyring.ckks.MsgSubmitGkgShare")
	proto.RegisterType((*MsgSubmitGkgShareResponse)(nil), "fairyring.ckks.MsgSubmitGkgShareResponse")
	proto.RegisterType((*MsgSubmitShamirShare)(nil), "fairyring.ckks.MsgSubmitShamirShare")
	proto.RegisterType((*MsgSubmitShamirShareResponse)(nil), "fairyring.ckks.MsgSubmitShamirShareResponse")
	proto.RegisterType((*MsgKeySwitchRequest)(nil), "fairyring.ckks.MsgKeySwitchRequest")
	proto.RegisterType((*MsgKeySwitchRequestResponse)(nil), "fairyring.ckks.MsgKeySwitchRequestResponse")
}

func init() { proto.RegisterFile("fairyring/ckks/tx.proto", fileDescriptor_a1c4b5cf36db7d93) }

var fileDescriptor_a1c4b5cf36db7d93 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x8f, 0xd2, 0x50,
	0x14, 0xa5, 0x4c, 0x18, 0xc3, 0x75, 0x82, 0x52, 0x89, 0x40, 0x19, 0x0b, 0x83, 0x26, 0x33, 0x32,
	0x4a, 0x33, 0x9d, 0xc4, 0xc4, 0xd9, 0x49, 0x54, 0x16, 0x4a, 0x42, 0x4a, 0x4c, 0xd4, 0x18, 0x27,
	0x8f, 0x52, 0x4b, 0x83, 0xe5, 0xd5, 0xbe, 0x87, 0x33, 0xec, 0x8c, 0x4b, 0x57, 0xfe, 0x0c, 0x97,
	0x2c, 0xdc, 0xf8, 0x0f, 0x66, 0x39, 0x71, 0xa5, 0x1b, 0x63, 0x60, 0xc1, 0xdf, 0x30, 0xfd, 0x44,
	0x4a, 0xb1, 0x5d, 0x38, 0x1b, 0xe0, 0xdd, 0x73, 0xee, 0x39, 0xe7, 0xdd, 0x70, 0xf3, 0x20, 0xff,
	0x06, 0x69, 0xe6, 0xd8, 0xd4, 0x86, 0xaa, 0x20, 0x0f, 0x06, 0x44, 0xa0, 0xa7, 0x75, 0xc3, 0xc4,
	0x14, 0xb3, 0x19, 0x1f, 0xa8, 0x5b, 0x00, 0x97, 0x45, 0xba, 0x36, 0xc4, 0x82, 0xfd, 0xe9, 0x50,
	0xb8, 0xbc, 0x8c, 0x89, 0x8e, 0x89, 0xa0, 0x13, 0x55, 0x78, 0x7f, 0x60, 0x7d, 0xb9, 0x40, 0xd1,
	0x01, 0x8e, 0xed, 0x93, 0xe0, 0x1c, 0x5c, 0x28, 0xa7, 0x62, 0x15, 0x3b, 0x75, 0xeb, 0x97, 0x5b,
	0x2d, 0x05, 0x52, 0x18, 0xc8, 0x44, 0xba, 0xdb, 0x52, 0xfd, 0xc6, 0xc0, 0x95, 0x16, 0x51, 0x9f,
	0x19, 0x3d, 0x44, 0x95, 0xb6, 0x8d, 0xb0, 0xf7, 0x20, 0x8d, 0x46, 0xb4, 0x8f, 0x4d, 0x8d, 0x8e,
	0x0b, 0x4c, 0x85, 0xd9, 0x4b, 0x37, 0x0a, 0xdf, 0xbf, 0xde, 0xcd, 0xb9, 0x5e, 0x0f, 0x7a, 0x3d,
	0x53, 0x21, 0xa4, 0x43, 0x2d, 0x49, 0x69, 0x41, 0x65, 0xef, 0xc3, 0xa6, 0xa3, 0x5d, 0x48, 0x56,
	0x98, 0xbd, 0xcb, 0xe2, 0xf5, 0xfa, 0xf2, 0x35, 0xeb, 0x8e, 0x7e, 0x23, 0x7d, 0xf6, 0xab, 0x9c,
	0xf8, 0x32, 0x9f, 0xd4, 0x18, 0xc9, 0x6d, 0x38, 0x3a, 0xfc, 0x38, 0x9f, 0xd4, 0x16, 0x52, 0x9f,
	0xe6, 0x93, 0x5a, 0x65, 0x11, 0xfb, 0xd4, 0x09, 0x1e, 0xc8, 0x59, 0x2d, 0x42, 0x3e, 0x50, 0x92,
	0x14, 0x62, 0xe0, 0x21, 0x51, 0xaa, 0x2f, 0x20, 0xdb, 0x22, 0x6a, 0x67, 0xd4, 0xd5, 0x35, 0xda,
	0x1e, 0xa8, 0x9d, 0x3e, 0x32, 0x15, 0xb6, 0x00, 0x97, 0x64, 0x53, 0x41, 0x14, 0x9b, 0xce, 0xad,
	0x24, 0xef, 0xc8, 0x6e, 0x43, 0x9a, 0x58, 0x94, 0x87, 0x88, 0x22, 0x3b, 0x7c, 0x5a, 0x5a, 0x14,
	0x8e, 0xb6, 0xac, 0x70, 0x1e, 0xb7, 0x5a, 0x82, 0xe2, 0x8a, 0xb4, 0xef, 0x7b, 0x6c, 0x47, 0x72,
	0x40, 0xc9, 0x03, 0xf1, 0x68, 0xd8, 0x3b, 0xf8, 0x4f, 0xee, 0x3b, 0x50, 0x5e, 0x63, 0x10, 0x9d,
	0x41, 0xbc, 0xe8, 0x0c, 0x62, 0xe8, 0xfc, 0x9b, 0x17, 0x37, 0xff, 0x66, 0x70, 0xfe, 0xaf, 0x20,
	0xe7, 0x83, 0x9d, 0x3e, 0xd2, 0x35, 0x33, 0xae, 0xf5, 0x53, 0x8d, 0xd0, 0x25, 0x6b, 0xab, 0x10,
	0xb0, 0xe6, 0x61, 0x3b, 0x4c, 0xdd, 0x77, 0x97, 0xe1, 0x5a, 0x8b, 0xa8, 0x4f, 0x94, 0x71, 0xe7,
	0x44, 0xa3, 0x72, 0x5f, 0x52, 0xde, 0x8d, 0x14, 0x42, 0xff, 0x61, 0x9e, 0x81, 0xa4, 0xec, 0xb9,
	0x26, 0x65, 0xca, 0xe6, 0x20, 0x35, 0x54, 0x4e, 0xda, 0x83, 0xc2, 0x86, 0x5d, 0x72, 0x0e, 0x81,
	0x10, 0x37, 0xa0, 0x14, 0x62, 0xe2, 0x65, 0x10, 0x7f, 0xa6, 0x60, 0xa3, 0x45, 0x54, 0xf6, 0x39,
	0x6c, 0x2d, 0x2d, 0x75, 0x39, 0xb8, 0x8c, 0x81, 0xd5, 0xe1, 0x76, 0x23, 0x08, 0x9e, 0x03, 0xfb,
	0x1a, 0x32, 0x81, 0xc5, 0xda, 0x09, 0x69, 0x5d, 0xa6, 0x70, 0xb7, 0x23, 0x29, 0xbe, 0xbe, 0x01,
	0xb9, 0xd0, 0x05, 0xda, 0x5d, 0x2b, 0xb1, 0x4c, 0xe4, 0x84, 0x98, 0xc4, 0x08, 0x47, 0x31, 0xae,
	0xa3, 0x18, 0xd7, 0x51, 0x5c, 0x9d, 0x61, 0x33, 0x7a, 0x86, 0xcd, 0xe8, 0x19, 0x06, 0xf7, 0x80,
	0x55, 0x21, 0xbb, 0xba, 0x04, 0xb7, 0xd6, 0xf6, 0xff, 0xc5, 0xe2, 0xee, 0xc4, 0x61, 0xf9, 0x46,
	0x3d, 0xb8, 0xba, 0xf2, 0x7f, 0xbf, 0x19, 0xa2, 0x10, 0x24, 0x71, 0xfb, 0x31, 0x48, 0x9e, 0x0b,
	0x97, 0xfa, 0x60, 0xbd, 0x16, 0x8d, 0x47, 0x67, 0x53, 0x9e, 0x39, 0x9f, 0xf2, 0xcc, 0xef, 0x29,
	0xcf, 0x7c, 0x9e, 0xf1, 0x89, 0xf3, 0x19, 0x9f, 0xf8, 0x31, 0xe3, 0x13, 0x2f, 0xf7, 0x55, 0x8d,
	0xf6, 0x47, 0xdd, 0xba, 0x8c, 0x75, 0xe1, 0x31, 0xd2, 0xcc, 0xee, 0x5b, 0x2c, 0x0f, 0x84, 0x95,
	0x17, 0x84, 0x8e, 0x0d, 0x85, 0x74, 0x37, 0xed, 0xa7, 0xef, 0xf0, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x77, 0xa7, 0x9c, 0x49, 0x9f, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	SubmitPkgShare(ctx context.Context, in *MsgSubmitPkgShare, opts ...grpc.CallOption) (*MsgSubmitPkgShareResponse, error)
	SubmitRkgShareRound1(ctx context.Context, in *MsgSubmitRkgShareRound1, opts ...grpc.CallOption) (*MsgSubmitRkgShareRound1Response, error)
	SubmitRkgShareRound2(ctx context.Context, in *MsgSubmitRkgShareRound2, opts ...grpc.CallOption) (*MsgSubmitRkgShareRound2Response, error)
	SubmitGkgShare(ctx context.Context, in *MsgSubmitGkgShare, opts ...grpc.CallOption) (*MsgSubmitGkgShareResponse, error)
	SubmitShamirShare(ctx context.Context, in *MsgSubmitShamirShare, opts ...grpc.CallOption) (*MsgSubmitShamirShareResponse, error)
	KeySwitchRequest(ctx context.Context, in *MsgKeySwitchRequest, opts ...grpc.CallOption) (*MsgKeySwitchRequestResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/fairyring.ckks.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitPkgShare(ctx context.Context, in *MsgSubmitPkgShare, opts ...grpc.CallOption) (*MsgSubmitPkgShareResponse, error) {
	out := new(MsgSubmitPkgShareResponse)
	err := c.cc.Invoke(ctx, "/fairyring.ckks.Msg/SubmitPkgShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitRkgShareRound1(ctx context.Context, in *MsgSubmitRkgShareRound1, opts ...grpc.CallOption) (*MsgSubmitRkgShareRound1Response, error) {
	out := new(MsgSubmitRkgShareRound1Response)
	err := c.cc.Invoke(ctx, "/fairyring.ckks.Msg/SubmitRkgShareRound1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitRkgShareRound2(ctx context.Context, in *MsgSubmitRkgShareRound2, opts ...grpc.CallOption) (*MsgSubmitRkgShareRound2Response, error) {
	out := new(MsgSubmitRkgShareRound2Response)
	err := c.cc.Invoke(ctx, "/fairyring.ckks.Msg/SubmitRkgShareRound2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitGkgShare(ctx context.Context, in *MsgSubmitGkgShare, opts ...grpc.CallOption) (*MsgSubmitGkgShareResponse, error) {
	out := new(MsgSubmitGkgShareResponse)
	err := c.cc.Invoke(ctx, "/fairyring.ckks.Msg/SubmitGkgShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitShamirShare(ctx context.Context, in *MsgSubmitShamirShare, opts ...grpc.CallOption) (*MsgSubmitShamirShareResponse, error) {
	out := new(MsgSubmitShamirShareResponse)
	err := c.cc.Invoke(ctx, "/fairyring.ckks.Msg/SubmitShamirShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) KeySwitchRequest(ctx context.Context, in *MsgKeySwitchRequest, opts ...grpc.CallOption) (*MsgKeySwitchRequestResponse, error) {
	out := new(MsgKeySwitchRequestResponse)
	err := c.cc.Invoke(ctx, "/fairyring.ckks.Msg/KeySwitchRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	SubmitPkgShare(context.Context, *MsgSubmitPkgShare) (*MsgSubmitPkgShareResponse, error)
	SubmitRkgShareRound1(context.Context, *MsgSubmitRkgShareRound1) (*MsgSubmitRkgShareRound1Response, error)
	SubmitRkgShareRound2(context.Context, *MsgSubmitRkgShareRound2) (*MsgSubmitRkgShareRound2Response, error)
	SubmitGkgShare(context.Context, *MsgSubmitGkgShare) (*MsgSubmitGkgShareResponse, error)
	SubmitShamirShare(context.Context, *MsgSubmitShamirShare) (*MsgSubmitShamirShareResponse, error)
	KeySwitchRequest(context.Context, *MsgKeySwitchRequest) (*MsgKeySwitchRequestResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) SubmitPkgShare(ctx context.Context, req *MsgSubmitPkgShare) (*MsgSubmitPkgShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPkgShare not implemented")
}
func (*UnimplementedMsgServer) SubmitRkgShareRound1(ctx context.Context, req *MsgSubmitRkgShareRound1) (*MsgSubmitRkgShareRound1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRkgShareRound1 not implemented")
}
func (*UnimplementedMsgServer) SubmitRkgShareRound2(ctx context.Context, req *MsgSubmitRkgShareRound2) (*MsgSubmitRkgShareRound2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRkgShareRound2 not implemented")
}
func (*UnimplementedMsgServer) SubmitGkgShare(ctx context.Context, req *MsgSubmitGkgShare) (*MsgSubmitGkgShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitGkgShare not implemented")
}
func (*UnimplementedMsgServer) SubmitShamirShare(ctx context.Context, req *MsgSubmitShamirShare) (*MsgSubmitShamirShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitShamirShare not implemented")
}
func (*UnimplementedMsgServer) KeySwitchRequest(ctx context.Context, req *MsgKeySwitchRequest) (*MsgKeySwitchRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeySwitchRequest not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairyring.ckks.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitPkgShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitPkgShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitPkgShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairyring.ckks.Msg/SubmitPkgShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitPkgShare(ctx, req.(*MsgSubmitPkgShare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitRkgShareRound1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitRkgShareRound1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitRkgShareRound1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairyring.ckks.Msg/SubmitRkgShareRound1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitRkgShareRound1(ctx, req.(*MsgSubmitRkgShareRound1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitRkgShareRound2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitRkgShareRound2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitRkgShareRound2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairyring.ckks.Msg/SubmitRkgShareRound2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitRkgShareRound2(ctx, req.(*MsgSubmitRkgShareRound2))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitGkgShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitGkgShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitGkgShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairyring.ckks.Msg/SubmitGkgShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitGkgShare(ctx, req.(*MsgSubmitGkgShare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitShamirShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitShamirShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitShamirShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairyring.ckks.Msg/SubmitShamirShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitShamirShare(ctx, req.(*MsgSubmitShamirShare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_KeySwitchRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgKeySwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).KeySwitchRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairyring.ckks.Msg/KeySwitchRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).KeySwitchRequest(ctx, req.(*MsgKeySwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fairyring.ckks.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SubmitPkgShare",
			Handler:    _Msg_SubmitPkgShare_Handler,
		},
		{
			MethodName: "SubmitRkgShareRound1",
			Handler:    _Msg_SubmitRkgShareRound1_Handler,
		},
		{
			MethodName: "SubmitRkgShareRound2",
			Handler:    _Msg_SubmitRkgShareRound2_Handler,
		},
		{
			MethodName: "SubmitGkgShare",
			Handler:    _Msg_SubmitGkgShare_Handler,
		},
		{
			MethodName: "SubmitShamirShare",
			Handler:    _Msg_SubmitShamirShare_Handler,
		},
		{
			MethodName: "KeySwitchRequest",
			Handler:    _Msg_KeySwitchRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fairyring/ckks/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitPkgShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPkgShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPkgShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ShareData) > 0 {
		i -= len(m.ShareData)
		copy(dAtA[i:], m.ShareData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ShareData)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitPkgShareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitPkgShareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitPkgShareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitRkgShareRound1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitRkgShareRound1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitRkgShareRound1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ShareData) > 0 {
		i -= len(m.ShareData)
		copy(dAtA[i:], m.ShareData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ShareData)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitRkgShareRound1Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitRkgShareRound1Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitRkgShareRound1Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitRkgShareRound2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitRkgShareRound2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitRkgShareRound2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ShareData) > 0 {
		i -= len(m.ShareData)
		copy(dAtA[i:], m.ShareData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ShareData)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitRkgShareRound2Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitRkgShareRound2Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitRkgShareRound2Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitGkgShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitGkgShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitGkgShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ShareData) > 0 {
		i -= len(m.ShareData)
		copy(dAtA[i:], m.ShareData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ShareData)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitGkgShareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitGkgShareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitGkgShareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitShamirShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitShamirShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitShamirShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ShareList) > 0 {
		i -= len(m.ShareList)
		copy(dAtA[i:], m.ShareList)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ShareList)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitShamirShareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitShamirShareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitShamirShareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgKeySwitchRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgKeySwitchRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgKeySwitchRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewPk) > 0 {
		i -= len(m.NewPk)
		copy(dAtA[i:], m.NewPk)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewPk)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Ct) > 0 {
		i -= len(m.Ct)
		copy(dAtA[i:], m.Ct)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Ct)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgKeySwitchRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgKeySwitchRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgKeySwitchRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitPkgShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ShareData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitPkgShareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitRkgShareRound1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ShareData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitRkgShareRound1Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitRkgShareRound2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ShareData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitRkgShareRound2Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitGkgShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ShareData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitGkgShareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitShamirShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ShareList)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitShamirShareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgKeySwitchRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Ct)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewPk)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgKeySwitchRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitPkgShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitPkgShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitPkgShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShareData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitPkgShareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitPkgShareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitPkgShareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitRkgShareRound1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitRkgShareRound1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitRkgShareRound1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShareData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitRkgShareRound1Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitRkgShareRound1Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitRkgShareRound1Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitRkgShareRound2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitRkgShareRound2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitRkgShareRound2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShareData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitRkgShareRound2Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitRkgShareRound2Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitRkgShareRound2Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitGkgShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitGkgShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitGkgShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShareData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitGkgShareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitGkgShareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitGkgShareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitShamirShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitShamirShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitShamirShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShareList = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitShamirShareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitShamirShareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitShamirShareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgKeySwitchRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgKeySwitchRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgKeySwitchRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ct", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ct = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewPk", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewPk = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgKeySwitchRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgKeySwitchRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgKeySwitchRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
