// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: cosmos/msg/textual/v1/textual.proto

/* eslint-disable */

export const protobufPackage = "cosmos.msg.textual.v1";
