// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fairyring/pep/genesis.proto

package types

import (
	fmt "fmt"
	types "github.com/Fairblock/fairyring/x/common/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the pep module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params            Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PortId            string                `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	EncryptedTxArray  []EncryptedTxArray    `protobuf:"bytes,3,rep,name=encryptedTxArray,proto3" json:"encryptedTxArray"`
	PepNonceList      []PepNonce            `protobuf:"bytes,4,rep,name=pepNonceList,proto3" json:"pepNonceList"`
	DecryptionKeyList []DecryptionKey       `protobuf:"bytes,6,rep,name=decryption_key_list,json=decryptionKeyList,proto3" json:"decryption_key_list"`
	ActivePubKey      types.ActivePublicKey `protobuf:"bytes,7,opt,name=activePubKey,proto3" json:"activePubKey"`
	QueuedPubKey      types.QueuedPublicKey `protobuf:"bytes,8,opt,name=queuedPubKey,proto3" json:"queuedPubKey"`
	RequestCount      uint64                `protobuf:"varint,9,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	RequestIdList     []RequestId           `protobuf:"bytes,10,rep,name=requestIdList,proto3" json:"requestIdList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c02ca82ac7a8fa8f, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *GenesisState) GetEncryptedTxArray() []EncryptedTxArray {
	if m != nil {
		return m.EncryptedTxArray
	}
	return nil
}

func (m *GenesisState) GetPepNonceList() []PepNonce {
	if m != nil {
		return m.PepNonceList
	}
	return nil
}

func (m *GenesisState) GetDecryptionKeyList() []DecryptionKey {
	if m != nil {
		return m.DecryptionKeyList
	}
	return nil
}

func (m *GenesisState) GetActivePubKey() types.ActivePublicKey {
	if m != nil {
		return m.ActivePubKey
	}
	return types.ActivePublicKey{}
}

func (m *GenesisState) GetQueuedPubKey() types.QueuedPublicKey {
	if m != nil {
		return m.QueuedPubKey
	}
	return types.QueuedPublicKey{}
}

func (m *GenesisState) GetRequestCount() uint64 {
	if m != nil {
		return m.RequestCount
	}
	return 0
}

func (m *GenesisState) GetRequestIdList() []RequestId {
	if m != nil {
		return m.RequestIdList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "fairyring.pep.GenesisState")
}

func init() { proto.RegisterFile("fairyring/pep/genesis.proto", fileDescriptor_c02ca82ac7a8fa8f) }

var fileDescriptor_c02ca82ac7a8fa8f = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6e, 0xd3, 0x4c,
	0x14, 0x85, 0xe3, 0xbf, 0x51, 0xfa, 0x67, 0x9a, 0x4a, 0xd4, 0x80, 0x6a, 0x05, 0x70, 0x4d, 0xbb,
	0x89, 0xba, 0xb0, 0xa5, 0xb2, 0x61, 0x9b, 0x10, 0x40, 0x55, 0x10, 0x6a, 0x0d, 0x2b, 0x36, 0x96,
	0x63, 0x5f, 0xdc, 0x51, 0x93, 0x99, 0xe9, 0x78, 0x8c, 0xe2, 0xb7, 0xe0, 0x31, 0x58, 0xf2, 0x18,
	0x5d, 0x66, 0xc9, 0x0a, 0xa1, 0x64, 0xc1, 0x6b, 0xa0, 0x19, 0x8f, 0x93, 0x8c, 0x11, 0x9b, 0x68,
	0x72, 0xef, 0x39, 0xdf, 0x5c, 0x9f, 0xb9, 0xe8, 0xc9, 0xe7, 0x18, 0xf3, 0x92, 0x63, 0x92, 0x05,
	0x0c, 0x58, 0x90, 0x01, 0x81, 0x1c, 0xe7, 0x3e, 0xe3, 0x54, 0x50, 0xfb, 0x70, 0xd3, 0xf4, 0x19,
	0xb0, 0xfe, 0x51, 0x3c, 0xc7, 0x84, 0x06, 0xea, 0xb7, 0x52, 0xf4, 0x1f, 0x65, 0x34, 0xa3, 0xea,
	0x18, 0xc8, 0x93, 0xae, 0xf6, 0x4d, 0x28, 0x8b, 0x79, 0x3c, 0xd7, 0xcc, 0xbe, 0x67, 0xf6, 0x80,
	0x24, 0xbc, 0x64, 0x02, 0xd2, 0x48, 0x2c, 0xb4, 0xe2, 0x59, 0xc3, 0x0d, 0x2c, 0x22, 0x94, 0x24,
	0xa0, 0xdb, 0xa7, 0x66, 0x3b, 0x05, 0x05, 0xc0, 0x94, 0x44, 0xb7, 0x50, 0x6a, 0xcd, 0xd9, 0x56,
	0x93, 0xd0, 0xf9, 0x9c, 0x92, 0x20, 0xbf, 0x89, 0xb9, 0xbc, 0xa4, 0x64, 0x50, 0x4f, 0xe2, 0x9a,
	0x20, 0x0e, 0x77, 0x05, 0xe4, 0x22, 0xc2, 0x69, 0xd5, 0x3f, 0x5d, 0xb6, 0x51, 0xef, 0x6d, 0x95,
	0xc7, 0x07, 0x11, 0x0b, 0xb0, 0x5f, 0xa2, 0x4e, 0xf5, 0x29, 0x8e, 0xe5, 0x59, 0x83, 0x83, 0x8b,
	0xc7, 0xbe, 0x91, 0x8f, 0x7f, 0xa5, 0x9a, 0xa3, 0xee, 0xfd, 0xcf, 0x93, 0xd6, 0xb7, 0xdf, 0xdf,
	0xcf, 0xad, 0x50, 0xeb, 0xed, 0x63, 0xb4, 0xcf, 0x28, 0x97, 0x6c, 0xe7, 0x3f, 0xcf, 0x1a, 0x74,
	0xc3, 0x8e, 0xfc, 0x7b, 0x99, 0xda, 0xd7, 0xe8, 0xc1, 0x26, 0x81, 0x8f, 0x8b, 0x21, 0xe7, 0x71,
	0xe9, 0xec, 0x79, 0x7b, 0x83, 0x83, 0x8b, 0x93, 0x06, 0xfc, 0x75, 0x43, 0x36, 0x6a, 0xcb, 0x6b,
	0xc2, 0xbf, 0xec, 0xf6, 0x10, 0xf5, 0x18, 0xb0, 0xf7, 0x32, 0xb1, 0x77, 0x38, 0x17, 0x4e, 0x5b,
	0xe1, 0x8e, 0x9b, 0xb3, 0x6a, 0x89, 0xc6, 0x18, 0x16, 0x3b, 0x44, 0x0f, 0xcd, 0x58, 0xa3, 0x99,
	0x24, 0x75, 0x14, 0xe9, 0x69, 0x83, 0x34, 0xde, 0x28, 0x27, 0x50, 0x4f, 0x75, 0x94, 0xee, 0x16,
	0x15, 0x73, 0x82, 0x7a, 0x71, 0x22, 0xf0, 0x17, 0xb8, 0x2a, 0xa6, 0x13, 0x28, 0x9d, 0x7d, 0x15,
	0xe1, 0xf3, 0x1d, 0x58, 0xf5, 0x52, 0xfe, 0xb0, 0x56, 0xcd, 0x70, 0xb2, 0x25, 0x1a, 0x66, 0x09,
	0xbb, 0x2b, 0xa0, 0x80, 0x54, 0xc3, 0xfe, 0xff, 0x17, 0xec, 0xba, 0x56, 0x99, 0xb0, 0x5d, 0xb3,
	0x7d, 0x86, 0x0e, 0xeb, 0xb7, 0x4f, 0x68, 0x41, 0x84, 0xd3, 0xf5, 0xac, 0x41, 0x3b, 0xec, 0xe9,
	0xe2, 0x2b, 0x59, 0xb3, 0xc7, 0x1b, 0xd1, 0x65, 0xaa, 0x62, 0x45, 0x2a, 0x0c, 0xa7, 0x11, 0x46,
	0x58, 0x6b, 0xf4, 0x4d, 0xa6, 0x69, 0x34, 0xbe, 0x5f, 0xb9, 0xd6, 0x72, 0xe5, 0x5a, 0xbf, 0x56,
	0xae, 0xf5, 0x75, 0xed, 0xb6, 0x96, 0x6b, 0xb7, 0xf5, 0x63, 0xed, 0xb6, 0x3e, 0x9d, 0x67, 0x58,
	0xdc, 0x14, 0x53, 0x39, 0x77, 0xf0, 0x26, 0xc6, 0x7c, 0x3a, 0xa3, 0xc9, 0x6d, 0xb0, 0xdd, 0xd0,
	0x85, 0xda, 0x51, 0xb5, 0xbe, 0xd3, 0x8e, 0xda, 0xcf, 0x17, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x36, 0x54, 0x1c, 0x79, 0xbc, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestIdList) > 0 {
		for iNdEx := len(m.RequestIdList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RequestIdList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.RequestCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RequestCount))
		i--
		dAtA[i] = 0x48
	}
	{
		size, err := m.QueuedPubKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.ActivePubKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.DecryptionKeyList) > 0 {
		for iNdEx := len(m.DecryptionKeyList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DecryptionKeyList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.PepNonceList) > 0 {
		for iNdEx := len(m.PepNonceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PepNonceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.EncryptedTxArray) > 0 {
		for iNdEx := len(m.EncryptedTxArray) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EncryptedTxArray[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.EncryptedTxArray) > 0 {
		for _, e := range m.EncryptedTxArray {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PepNonceList) > 0 {
		for _, e := range m.PepNonceList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DecryptionKeyList) > 0 {
		for _, e := range m.DecryptionKeyList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.ActivePubKey.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.QueuedPubKey.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.RequestCount != 0 {
		n += 1 + sovGenesis(uint64(m.RequestCount))
	}
	if len(m.RequestIdList) > 0 {
		for _, e := range m.RequestIdList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedTxArray", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedTxArray = append(m.EncryptedTxArray, EncryptedTxArray{})
			if err := m.EncryptedTxArray[len(m.EncryptedTxArray)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PepNonceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PepNonceList = append(m.PepNonceList, PepNonce{})
			if err := m.PepNonceList[len(m.PepNonceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DecryptionKeyList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DecryptionKeyList = append(m.DecryptionKeyList, DecryptionKey{})
			if err := m.DecryptionKeyList[len(m.DecryptionKeyList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivePubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActivePubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueuedPubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.QueuedPubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestCount", wireType)
			}
			m.RequestCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestIdList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestIdList = append(m.RequestIdList, RequestId{})
			if err := m.RequestIdList[len(m.RequestIdList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
